scribblr_prompts = [ #https://www.scribbr.com/ai-tools/best-ai-image-prompts/
    "A photo of a writer looking at her computer; she’s extremely happy with her work.", 
    "A misty sunset on the west coast of Vancouver Island", 
    "A medieval knight in shining armor holding a banner, painted in renaissance style", 
    "A photorealistic portrait of a young artist with paint on her hands and clothes", 
    "A cybernetic hacker with glowing eyes sitting in front of cascading digital code", 
    "Realistic close-up of a child laughing in the rain, droplets frozen midair", 
    "Street-style fashion portrait of a model in bold neon clothing under city lights", 
    "A pirate captain with a feathered hat and scarred face, painted in oil painting style", 
    "Realistic portrait of a ballet dancer stretching backstage in soft light", 
    "A steampunk explorer with brass gadgets, standing in front of a giant airship", 
    "A witch brewing potions in a candlelit cottage, painted in dark fantasy style", 
    "Otherworldly alien diplomat in elegant robes with shimmering, iridescent skin", 
    "Cartoon-style adventurer child with a backpack and a treasure map", 
    "A futuristic eco-city built into the side of a mountain with hanging gardens", 
    "A rainy European cobblestone street at night lit by warm lanterns", 
    "A bustling night market in an East Asian city with glowing lanterns and food stalls", 
    "An ancient Roman amphitheater reconstructed in photorealistic detail", 
    "A minimalist Japanese tea house surrounded by raked sand gardens", 
    "An arctic research station under the northern lights", 
    "A Moroccan bazaar filled with textiles, spices, and intricate archways", 
    "A cinematic view of skyscrapers piercing through thick clouds at dawn", 
    "A city skyline during a thunderstorm, with lightning illuminating glass towers", 
    "A neon-drenched Times Square–style district filled with holographic billboards", 
    "A fantasy dwarven city carved into the walls of a glowing crystal cavern", 
    "Abstract oil painting with swirling brushstrokes in bold reds and blues", 
    "Cubist-inspired still life with fragmented bottles and fruit in vibrant colors", 
    "Digital glitch art with distorted rainbow pixels and broken textures", 
    "Dreamlike portrait of a person dissolving into butterflies", 
    "Glowing neon wireframe sphere suspended in black space", 
    "Stained-glass window with intricate geometric symmetry", 
    "A surreal melting city skyline reflected in liquid mirrors", 
    "Chaotic abstract typography collage in the style of Dadaism", 
    "Minimalist line art drawing of two hands almost touching", 
    "Sculpture made of glass shards glowing under neon light", 
    "Vibrant and glowing deep-sea creature painted using pointillism technique", 
    "Illustrated cross-section of a volcano with labeled magma chamber, vent, and crater", 
    "Step-by-step infographic of the life cycle of a butterfly with clear icons and arrows", 
    "Clean diagram of the human skeletal system with labeled bones", 
    "Infographic showing the process of the carbon cycle with arrows and icons", 
    "Labeled cutaway diagram of a car engine in a technical manual style", 
    "Step-by-step visual guide to the scientific method using simple icons", 
    "Timeline infographic showing major events in ancient Egyptian history", 
    "Illustrated guide to the life cycle of a frog with labeled stages", 
    "Diagram of a medieval ship with labeled sails, mast, and hull parts", 
    "Infographic illustrating how a rainbow forms, with sunlight and raindrop interactions", 
    "Simple diagram depicting the water cycle", 
    "Flat lay of artisanal chocolate bars on a rustic wooden table, natural lighting", 
    "Instagram-ready photo of a smoothie bowl with vibrant fruits and granola", 
    "YouTube thumbnail of a surprised chef holding a giant sandwich with bright lighting", 
    "Business card mockup with embossed logo on a marble desk background", 
    "Mockup of a smartphone screen showing a lifestyle app interface in photorealistic style", 
    "Instagram carousel mockup featuring trendy stationery and notebooks", 
    "Product packaging concept for a craft beer bottle with illustrated label", 
    "Realistic coffee shop scene with branded cups, pastries, and napkins", 
    "Minimalist logo reveal mockup rendered on a concrete wall with soft shadow", 
    "A colorful app icon concept displayed on a modern smartphone screen in perspective view", 
    "Flat lay of eco-friendly yoga gear, including mat, blocks, and straps, styled aesthetically", 
    "Cartoon-style raccoon chef flipping pancakes in a busy diner", 
    "Cute anime dragon blowing soap bubbles instead of fire", 
    "Digital art of a koala DJ spinning records at a neon dance club", 
    "Adorable hamster astronaut riding a rocket shaped like a carrot", 
    "Cute puppy dressed as a pirate steering a toy ship", 
    "Cartoon-style sloth superhero flying clumsily through the sky", 
    "Charming hedgehog painter creating a masterpiece on a giant canvas", 
    "Whimsical cat mermaid lounging on a rock in a pastel ocean", 
    "Fantasy-style mouse knight in tiny shining armor holding a sword", 
    "Cartoon llama riding a unicycle while holding balloons", 
    "Magical unicorn barista serving rainbow lattes in a cozy café", 
    "Put me in a blouse and pencil skirt instead of casual clothes", 
    "Remove all the people in the background of this photo", 
    "Remove blemishes and shiny foreheads in this group shot", 
    "Show me what this room would look like with light blue walls", 
    "Add a sunset sky behind this city skyline", 
    "Turn this photo into a pencil sketch", 
    "Replace this wedding bouquet with sunflowers", 
    "Change the season in this photo from summer to winter", 
    "Put everyone in this family portrait in matching red flannel shirts", 
    "Add a golden retriever sitting next to me in this picture", 
    "Give the Mona Lisa eyebrows",
    "Create an image of an owl drawn with oil paint", 
    "Create an image of an owl drawn with crayons", 
    "Create an image of an owl drawn with watercolor paint", 
    "Create an image of an owl drawn with line art", 
    "Draw an owl made of food.", 
    "Draw a forest in Gothic medieval style.", 
    "Draw a forest in Renaissance style.", 
    "Draw a forest in Impressionist style.", 
    "Draw a forest in an Expressionist style.", 
    "A wristwatch in the style of Johannes Vermeer.", 
    "A wristwatch in the style of Vincent Van Gogh.", 
    "A wristwatch in the style of Rembrandt.", 
    "A side-by-side comparison of portrait and fashion photography"
]

stockimg_prompts = [ #https://stockimg.ai/blog/design-and-creativity/20-unique-prompts-for-ai-image-generation
    "A minimalist watercolor painting of a sunrise over a calm sea, with soft brushstrokes and muted colors",
    "Cubist depiction of a city skyline with overlapping perspectives and vibrant geometric shapes",
    "Surreal landscape in the style of Salvador Dalí, featuring melting clocks and strange, distorted objects",
    "Impasto oil painting of Marilyn Monroe, heavy strokes, textured, stunning digital illustration, elegant, calm, mysterious, digital painting, expressionism style, very intricate, unforgettable",
    "A portrait of a young woman in natural light, with a soft bokeh background and warm, golden tones",
    "Nighttime cityscape with reflections on wet pavement, featuring neon lights in the distance",
    "Macro photograph of a dew-covered spider web, sparkling in the early morning sun",
    "A professional photo of a beautiful woman in a polka-dot dress laying on grass. Top down shot",
    "A dragon perched on a cliff overlooking a futuristic city, with glowing neon lights and flying cars",
    "Alien landscape with two suns setting, purple skies, and towering crystal formations",
    "A mystical forest filled with bioluminescent plants and a glowing river under a starry sky",
    "A girl astronaut exploring the cosmos, floating among planets and stars, high quality detail, anime screencap, studio Ghibli style, illustration, high contrast, masterpiece, best quality",
    "A beautiful, anime-style portrait of a young girl with expressive eyes, wearing a futuristic astronaut helmet, vibrant orange and pink flowers surrounding the helmet, surreal composition",
    "Studio shot of a luxury wristwatch on a reflective black surface, with a spotlight highlighting the intricate details",
    "A pair of running shoes against a textured background, showing the soles covered in trail dirt to suggest outdoor adventure",
    "Glass perfume bottle with a gradient background, featuring floating flower petals around it",
    "A cyberpunk-style female character with neon blue hair and augmented reality glasses, standing in a crowded futuristic market",
    "Medieval knight in ornate armor, with a red plume on their helmet, posing heroically against a castle backdrop",
    "A whimsical forest creature with oversized ears and a mischievous grin, surrounded by glowing fireflies",
    "Portrait of a large wolf covered in a cloud of smoke, whirlwind, red highlight colors, black fur, majestic, hints of pastel, misty, sultry, breathtaking, oil painting style, artistic, aesthetic modern art, hyper-realism, line art",
    "Masterpiece, best quality, girl, collarbone, wavy hair, looking at viewer, blurry foreground, upper body, necklace, contemporary, plain pants, intricate, print, pattern, ponytail, freckles, red hair, dappled sunlight, smile, happy"
]

objects = [
    'parrot',
    'elephant',
    'zebra',
    'vintage camera',
    'acoustic guitar',
    'classic car',
    'robot assistant',
    'steampunk airship',
    'ceramic teapot',
    'samurai helmet',
    'glass perfume bottle',
    'retro arcade machine',
    'futuristic drone',
    'old typewriter',
    'gold pocket watch',
    'ancient compass',
    'crystal skull',
    'marble statue bust',
    'wooden toy train',
    'Victorian clock',
    'medieval shield',
    'fountain pen',
    'potted bonsai tree',
    'space rover',
    'candle lantern',
    'old radio',
    'smartphone hologram',
    'pirate treasure chest',
    'astronaut helmet',
    'dragon figurine',
    'ballet shoes',
    'antique globe',
    'neon sign board',
    'casette player',
    'cybernetic arm',
    'vintage bicycle',
    'skateboard',
    'hot air balloon',
    'katana sword',
    'futuristic motorbike',
    'toy robot',
    'glass chess set',
    'magic wand',
    'crystal orb',
    'film projector',
    'sailing ship model',
    'lunar telescope',
    'ancient book of spells',
    'mythical phoenix sculpture'
]

backgrounds = [
    'forest',
    'city',
    'desert',
    'mountains',
    'tropical beach',
    'savanna',
    'jungle ruins',
    'snowy tundra',
    'volcanic landscape',
    'rainy urban alley',
    'futuristic skyline',
    'old european village',
    'coral reef underwater world',
    'countryside fields',
    'enchanted magic forest',
    'abandoned amusement park',
    'deep space nebula',
    'ancient Greek temple',
    'Victorian London streets',
    'medieval castle courtyard',
    'post-apocalyptic wasteland',
    'steampunk industrial city',
    'cyberpunk neon district',
    'floating sky islands',
    'mystical crystal cave',
    'arctic ice cave',
    'stormy ocean cliffs',
    'hidden bamboo grove',
    'marble palace interior',
    'Arabian desert bazaar',
    'Tokyo night street',
    'retro 80s arcade hall',
    'underground subway tunnel',
    'cloud kingdom above the earth',
    'futuristic biotech lab',
    'outer space asteroid base',
    'haunted Victorian mansion',
    'abandoned space station',
    'robot factory assembly line',
    'high mountain monastery',
    'Aztec jungle temple',
    'Nordic fjord cliffs',
    'fantasy dwarven mine',
    'library with infinite shelves',
    'alien desert with twin suns',
    'lush waterfall canyon',
    'submerged ancient city',
    'moon surface base'
]


backgrounds = [
    'forest',
    'city',
    'desert',
    'mountains',
    'tropical beach',
    'savanna',
    'jungle ruins',
    'snowy tundra',
    'volcanic landscape',
    'rainy urban alley',
    'futuristic skyline',
    'old european village',
    'coral reef underwater world',
    'countryside fields',
    'enchanted magic forest',
    'abandoned amusement park',
    'deep space nebula',
    'ancient Greek temple',
    'Victorian London streets',
    'medieval castle courtyard',
    'post-apocalyptic wasteland',
    'steampunk industrial city',
    'cyberpunk neon district',
    'floating sky islands',
    'mystical crystal cave',
    'arctic ice cave',
    'stormy ocean cliffs',
    'hidden bamboo grove',
    'marble palace interior',
    'Arabian desert bazaar',
    'Tokyo night street',
    'retro 80s arcade hall',
    'underground subway tunnel',
    'cloud kingdom above the earth',
    'futuristic biotech lab',
    'outer space asteroid base',
    'haunted Victorian mansion',
    'abandoned space station',
    'robot factory assembly line',
    'high mountain monastery',
    'Aztec jungle temple',
    'Nordic fjord cliffs',
    'fantasy dwarven mine',
    'library with infinite shelves',
    'alien desert with twin suns',
    'lush waterfall canyon',
    'submerged ancient city',
    'moon surface base'
]

styles = [
    'black and white',
    'neon colors',
    'japanese anime style',
    'watercolor painting',
    'oil painting renaissance style',
    'cyberpunk aesthetic',
    'minimalist line art',
    'retro 80s synthwave',
    'surreal dreamlike style',
    'pixel art style',
    'steampunk illustration',
    'hyperrealistic photography',
    'pastel kawaii style',
    'noir comic book style',
    'futuristic hologram style',
    'baroque painting style',
    'low-poly 3D style',
    'vaporwave aesthetic',
    'charcoal sketch',
    'gothic illustration',
    'claymation style',
    'storybook illustration',
    'retro futurism style',
    'isometric rendering',
    'abstract expressionism',
    'cubism inspired style',
    'digital matte painting',
    'pop art style',
    'Ukiyo-e japanese woodblock style',
    'Art Nouveau illustration',
    'glitch effect aesthetic',
    'cinematic lighting style',
    'HDR hyperrealism',
    'chalkboard drawing',
    'blueprint technical style',
    'biomechanical art',
    'luxury fashion editorial style',
    'dark fantasy gritty style',
    'neoclassical sculpture style',
    'psychedelic rainbow palette',
    'impressionist painting',
    'children’s book pastel style',
    'origami paper craft style',
    '3D Pixar-style rendering',
    'AI-generated abstract fractal style',
    'photorealistic studio lighting',
    'stained glass style',
    'comic manga speedline style',
    'liquid metal reflective style'
]


